package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.BookGenre;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface BookGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    int insert(BookGenre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOOK_GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    List<BookGenre> selectAll();
}