package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Genre;
import org.mybatis.cdi.Mapper;
import java.util.List;
@Mapper
public interface GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    int insert(Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    Genre selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    List<Genre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Wed Mar 08 12:59:08 EET 2023
     */
    int updateByPrimaryKey(Genre record);
}